### ISSUE TITLE
Error while evaliation

### ISSUE THREAD

**Issue by Avi241** [mic-rud/GuidedDecoding#6]
Hi, This is really great work. I want to try your work but facing this error while running the evaluation.
Steps I did:
1. Downloaded and renamed the Model as GuideDepth bcoz that is what the model_builder function accepts.
2. Downloaded the Kiiti dataset(which you have provided) extracted it and created a tests folder in it and moved all the NumPy files to the tests folder.
3. I was getting an error of  ' AttributeError: 'AverageMeter' object has no attribute 'sum_rmse_log' ' so initialized self.sum_rmse_log=0 in metrics.py
4. Run the code with this arguments `python3 main.py --eval --dataset kitti --resolution full --model GuideDepth --test_path KITTI_test/` Now I am getting following error. Can you please help me with this ?

`Namespace(batch_size=8, data_path='kitti_comb', dataset='kitti', eval_mode='alhashim', evaluate=True, learning_rate=0.0001, load_checkpoint='', model='GuideDepth', num_epochs=20, num_workers=2, resolution='full', save_checkpoint='./checkpoints', save_results='./results', scheduler_step_size=15, test_path='KITTI_test/', train=False, weights_path=None)
Resolution for Eval: (384, 1280)
Maximum Depth of Dataset: 80.0
Traceback (most recent call last):
  File "main.py", line 113, in <module>
    main()
  File "main.py", line 110, in main
    evaluation_module.evaluate()
  File "/home/control/GuidedDecoding/evaluate.py", line 88, in evaluate
    data = self.to_tensor(packed_data)
  File "/home/control/GuidedDecoding/data/transforms.py", line 89, in __call__
    image, depth = transformation(image), transformation(depth)
  File "/home/control/anaconda3/envs/torch_0.4.1/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 76, in __call__
    return F.to_tensor(pic)
  File "/home/control/anaconda3/envs/torch_0.4.1/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 48, in to_tensor
    img = torch.from_numpy(pic.transpose((2, 0, 1)))
ValueError: axes don't match array`

Thank you.

**Comment by mic-rud** [comment]
Partially fixed by @miRemid in #10
